config/routes.rb
Rails.application.routes.draw do
  

  root 'top#top'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top/top'
  get 'top/about'
  resources :users
  resources :post_books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_book.rb
class PostBook < ApplicationRecord
    
    belongs_to :user
    
    validates :title, presence: true
    validates :opinion, presence: true
    validates :opinion,length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_books, dependent: :destroy
  attachment :profile_image
  
  validates :name,
    length: { minimum: 2, maximum: 20 }
  validates :introduction,
    length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    top_top_path
  end
  
  
  
  protected
  
  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/post_books_controller.rb
class PostBooksController < ApplicationController
    
    def index
        @post_books = PostBook.all
        @post_book = PostBook.new
        @user = current_user
    end
    
    def show
        @post_book = PostBook.new
        @post_books = PostBook.find(params[:id])
        @user = @post_books.user
    end
    
    def edit
        @post_book = PostBook.find(params[:id])
    end
    
    def create
        @post_book = PostBook.new(post_book_params)
        @post_book.user_id = current_user.id
        if @post_book.save
            flash[:notice] = 'You have created book successfully.'
            redirect_to post_books_path
        else
            @post_books = PostBook.all
            @user = current_user
            render 'index'
        end
    end
    
     def update
        @post_book = PostBook.find(params[:id])
        if @post_book.update(post_book_params)
            flash[:notice]  = 'You have updated book successfully.'
            redirect_to post_books_path
        else
            render :edit
        end
    end
    
    def destroy
	    @post_book = PostBook.find(params[:id])
	    @post_book.destroy
	    redirect_to post_books_path(@post_book.user_id)
	end
    
    private
    
    def post_book_params
        params.require(:post_book).permit(:title, :opinion)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
        @user = current_user
        @post_book = PostBook.new   
    end
    
    def show
        @user = User.find(params[:id])
        @post_books = @user.post_books
        @post_book = PostBook.new
    end
    
    def edit
        @user = User.find(params[:id])
    end
    
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = 'You have created book successfully.'
            redirect_to user_path(@user.id)
        else
            render :edit
        end
    end
    
    
    
    private
    def user_params
        params.require(:user).permit(:name, :introduction, :profile_image)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_books_helper.rb
module PostBooksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_sidebar.html.erb
<div class="side-bar">
	<div class="user-info">
			
		<h1>User Info</h1>
		<div class="profile-image">
			<%= attachment_image_tag @user, :profile_image,  size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
		</div>
		</br>
        <table class="table table-striped">
    	<tr>
        	<th>Name</th>
        	<td><%= @user.name %></td>
    	</tr>
    	<tr>
        	<th>Introduction</th>
			<td><%= @user.introduction %></td>
		</tr>
	   	</table>
		   	<% if current_user == @user %>
		   		<%= link_to edit_user_path(@user), :class=>"btn btn-default profile-btn" do %><i class="fas fa-wrench"></i><% end %>
		   	<% else %>
		   		<%= link_to (user_path(current_user.id)),:class=>"btn btn-default profile-btn" do %><i class="fas fa-wrench"></i><% end %>
		   	<% end %>
        	
	</div>
    <div class="post-form">
		<%= form_for(@post_book, url: post_books_path) do |f| %>
            <h3>TITLE</h3>
            <%= f.text_field :title %>
            <h3>OPINION</h3>
            <%= f.text_area :opinion %>
            </br>
            <%= f.submit 'CREATE BOOK', :class=>"btn btn-block btn-primary btn-lg" %>
           	<% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>
    <header>
        <div class="header-content clearfix">
            <h1 class="header-logo">Bookers</h1>
        <% if user_signed_in? %> <!-- ユーザーがログインしているか調べる -->
	    <nav class="header-nav">
		    <ul class="header-nav-list">
			    <li class="header-nav-item nav-home"><%= link_to (user_path(current_user.id)), :class=>"glyphicon glyphicon-home" do %> Home<% end %></li>
			    <li class="header-nav-item nav-users"><%= link_to users_path, :class=>"glyphicon glyphicon-user" do %> Users<% end %></li>
			    <li class="header-nav-item nav-books"><%= link_to post_books_path, :class=>"glyphicon glyphicon-book" do %> Books<% end %></li>
			    <li class="header-nav-item nav-logout"><%= link_to destroy_user_session_path, method: :delete, :class=>"glyphicon glyphicon-log-out" do %>Log out<% end %></li>
		    </ul>
		</nav>
        <% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
        <nav class="header-nav">
		    <ul class="header-nav-list">
		      <li class="header-nav-item"><p><%= link_to root_path, :class=>"glyphicon glyphicon-home" do %> HOME</p><% end %></li>
		      <li class="header-nav-item"><p><%= link_to top_about_path, :class=>"glyphicon glyphicon-link" do %> about</p><% end %></li>
			    <li class="header-nav-item"><p><%= link_to new_user_registration_path, :class=>"glyphicon glyphicon-edit" do %> Sign_up</p><% end %></li>
			    <li class="header-nav-item"><p><%= link_to new_user_session_path, :class=>"glyphicon glyphicon-log-in" do %> login</p><% end %></li>
		    </ul>
	    </nav>
	    <% end %>
	    </div>
    
    </header>
    <main>

    <div class="container">
            <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
          <%= yield %>
    </div>
    </main>
    <footer>
      <div class="footer-content clearfix">
        <h4>CopyRight Infratop.inc</h4>
      </div>
    </footer>      
  </body>
</html>

app/views/layouts/application.html.haml
- flash.each do |type, msg|
  %div{class: "alert alert-#{type}"}= msg

app/views/post_books/edit.html.erb
<% @post_book.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
        <%= message %>
     </div>
<% end %>

<h1>Editing Book</h1>

<div class="post-form">
		<%= form_for(@post_book) do |f| %>
            <h3>TITLE</h3>
            <%= f.text_field :title %>
            <h3>Opinion</h3>
            <%= f.text_area :opinion %>
            </br>
            <%= f.submit 'Update Book', :class=>"btn btn-primary btn-lg" %>
        <% end %>
</div>

app/views/post_books/index.html.erb
<% @post_book.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
        <%= message %>
     </div>
<% end %>
<div class="col-xs-3">
    <%= render :partial => "layouts/sidebar" %>
</div>

<div class="col-xs-9">
    <table class="table table-hover">
        <tr>
            <th></th>
            <th>TITLE</th>
            <th>OPINION</th>
        </tr>
        <% @post_books.each do |post_book| %>
        <tr>
            <td><%= link_to user_path(post_book.user.id) do %><%= attachment_image_tag post_book.user, :profile_image,  size: "30x30", format: 'jpeg', fallback: "no_image.jpg" %><% end %></td>
            <td><%= link_to post_book_path(post_book.id) do %><%= post_book.title %><% end %></td>
            <td><%= post_book.opinion %></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/post_books/show.html.erb
<div class="col-xs-3">
    <%= render :partial => "layouts/sidebar" %>
</div>

<div class="col-xs-9">
    <h1>Book detail</h1>
    <table class="table table-hover">
        <tr>
            <td><%= link_to user_path(@user.id) do %><%= attachment_image_tag @user, :profile_image,  size: "30x30", format: 'jpeg', fallback: "no_image.jpg" %><br><%= @user.name %><% end %></td>
            <td><%= @post_books.title %></td>
            <td><%= @post_books.opinion %></td>
            <% if @post_books.user.id == current_user.id %>
            <td><%= link_to edit_post_book_path(@post_books.id), :class=> "btn btn-success" do %>edit<% end %></td>
            <td><%= link_to "Destroy", post_book_path(@post_books), method: :delete , :class=> "btn btn-danger"%></td>
            <% end %>
        </tr>
    </table>
</div>

app/views/top/about.html.erb
<h1>welcome to <span class="glyphicon glyphicon-book"></span><spam class="bookers">Bookers !!</spam></h1>

app/views/top/top.html.erb
<div class="container">
    <div class="welcome row">
        <h1>welcome to <span class="glyphicon glyphicon-book"></span><spam class="bookers">Bookers !!</spam></h1>
        <p>In <span class="glyphicon glyphicon-book"></span>Bookers,<br>you can share and exchange your opinions , inpressions , and emotions <br>about varioius books!</p>
    </div>
    <div class="row">
        <div><%= link_to 'Log in', new_user_session_path, class: "btn btn-block btn-primary btn-lg" %></div>
        <div><%= link_to 'Sign_up', new_user_registration_path, class: "btn btn-block btn-success btn-lg" %></div>
    </div>    
</div>

app/views/users/edit.html.erb
<% @user.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
        <%= message %>
     </div>
<% end %>


<div class="post-form">
		<%= form_for(@user) do |f| %>
            <h3>Name</h3>
            <%= f.text_field :name %>
            <h3>Introduction</h3>
            <%= f.text_area :introduction %>
            
            <div class="user-edit-image">
                <br>
                <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
            </div>
            
            </br>
            <%= f.submit 'Profile Update', :class=>"btn btn-primary btn-lg" %>
        <% end %>
</div>

app/views/users/index.html.erb
<div class="col-xs-3">
    <%= render :partial => "layouts/sidebar" %>
</div>
<div class="col-xs-9">
    <h1>Users</h1>
    <table class="table table-hover">
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th></th>
        </tr>
        <% @users.each do|user| %>
        <tr>
            <td><%= attachment_image_tag user, :profile_image,  size: "30x30", format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%= link_to 'show', user_path(user.id) %></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/users/show.html.erb
<div class="col-xs-3">
    <%= render :partial => "layouts/sidebar" %>
</div>

<div class="col-xs-9">
    <h1><%= @user.name %></h1>
    <table class="table table-hover">
        <tr>
            <th>Image</th>
            <th>TITLE</th>
            <th>OPINION</th>
        </tr>
        <% @post_books.each do |post_book| %>
        <tr>
            <td><%= attachment_image_tag post_book.user, :profile_image,  size: "30x30", format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td><%= link_to post_book_path(post_book.id) do %><%= post_book.title %><% end %></td>
            <td><%= post_book.opinion %></td>
        </tr>
        <% end %>
    </table>
</div>